CREATE DATABASE IF NOT EXISTS `aelita_null`;
CREATE DATABASE IF NOT EXISTS `edition1`;
CREATE USER 'aelita_dev'@'%' IDENTIFIED BY 'codeaelitadev';

GRANT
    CREATE, ALTER, DROP, INDEX, INSERT, UPDATE, DELETE, SELECT, REFERENCES, CREATE TEMPORARY TABLES
        on aelita_null.* TO 'aelita_dev'@'%';
GRANT
    CREATE, ALTER, DROP, INDEX, INSERT, UPDATE, DELETE, SELECT, REFERENCES, CREATE TEMPORARY TABLES
        on edition1.* TO 'aelita_dev'@'%';
FLUSH PRIVILEGES;
